# Generated by Django 5.0.4 on 2024-04-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductMedia',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
