# Generated by Django 4.2 on 2024-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=255, verbose_name='слаг')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('image', models.ImageField(default=None, upload_to='image/products/', verbose_name='фото')),
                ('bio', models.TextField()),
                ('dateborth', models.DateField()),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='product.category', verbose_name='категории'),
        ),
    ]
