# Generated by Django 4.2 on 2024-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_author_remove_product_categories_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(to='product.author', verbose_name='авторы'),
        ),
    ]
